name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pigments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://fireredninja.github.io/cs-notes/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://fireredninja.github.io/cs-notes/'
author:         'Your Name'
