name: Computer Science Notes
description: My notes on CS Level 3
meta_description: "My CS notes"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: '/cs-notes'
domain_name: 'https://fireredninja.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://fireredninja.github.io/cs-notes/'

# Author details.
noel:
  name: Noel Rajan
dasha:
  name: Dasha Shumitskiy
andrew:
  name: Andrew McNab

# Site settings
excerpt_separator: <!--excerpt-->